-- VeriCargo OneTruth: account-level bootstrap.
-- Run with a role allowed to create warehouses and databases.

CREATE WAREHOUSE IF NOT EXISTS VERICARGO_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS VERICARGO_ONETRUTH;
CREATE SCHEMA IF NOT EXISTS VERICARGO_ONETRUTH.RAW;
CREATE SCHEMA IF NOT EXISTS VERICARGO_ONETRUTH.CURATED;
CREATE SCHEMA IF NOT EXISTS VERICARGO_ONETRUTH.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS VERICARGO_ONETRUTH.APP;

USE WAREHOUSE VERICARGO_WH;
USE DATABASE VERICARGO_ONETRUTH;

CREATE OR REPLACE FILE FORMAT RAW.CSV_HEADER_FORMAT
  TYPE = CSV
  PARSE_HEADER = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('', 'NULL');

CREATE STAGE IF NOT EXISTS RAW.CSV_STAGE
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE STAGE IF NOT EXISTS RAW.DOCUMENT_STAGE
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
