USE WAREHOUSE VERICARGO_WH;
USE DATABASE VERICARGO_ONETRUTH;

CREATE TABLE IF NOT EXISTS RAW.SUPPLIERS (
  SUPPLIER_ID VARCHAR NOT NULL,
  SUPPLIER_NAME VARCHAR NOT NULL,
  COUNTRY VARCHAR NOT NULL,
  RISK_TIER VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW.PARTS (
  PART_ID VARCHAR NOT NULL,
  SUPPLIER_ID VARCHAR NOT NULL,
  PART_NAME VARCHAR NOT NULL,
  UNIT_COST_USD NUMBER(18, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW.PLANTS (
  PLANT_ID VARCHAR NOT NULL,
  PLANT_NAME VARCHAR NOT NULL,
  COUNTRY VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW.CUSTOMERS (
  CUSTOMER_ID VARCHAR NOT NULL,
  CUSTOMER_NAME VARCHAR NOT NULL,
  COUNTRY VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW.PORTS (
  PORT_CODE VARCHAR NOT NULL,
  PORT_NAME VARCHAR NOT NULL,
  COUNTRY VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW.ORDERS (
  ORDER_ID VARCHAR NOT NULL,
  CUSTOMER_ID VARCHAR NOT NULL,
  PLANT_ID VARCHAR NOT NULL,
  ORDER_DATE DATE NOT NULL,
  PROMISED_DELIVERY_DATE DATE NOT NULL,
  STATUS VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW.ORDER_LINES (
  ORDER_ID VARCHAR NOT NULL,
  LINE_NUMBER NUMBER(10, 0) NOT NULL,
  PART_ID VARCHAR NOT NULL,
  ORDERED_QTY NUMBER(18, 3) NOT NULL,
  SHIPPED_QTY NUMBER(18, 3) NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW.SHIPMENTS (
  SHIPMENT_ID VARCHAR NOT NULL,
  ORDER_ID VARCHAR NOT NULL,
  SUPPLIER_ID VARCHAR NOT NULL,
  ORIGIN_PORT_CODE VARCHAR NOT NULL,
  DESTINATION_PORT_CODE VARCHAR NOT NULL,
  CONTAINER_ID VARCHAR NOT NULL,
  SHIP_DATE DATE NOT NULL,
  PROMISED_DELIVERY_DATE DATE NOT NULL,
  ACTUAL_DELIVERY_DATE DATE,
  STATUS VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW.SHIPMENT_EVENTS (
  EVENT_ID VARCHAR NOT NULL,
  SHIPMENT_ID VARCHAR NOT NULL,
  EVENT_TS TIMESTAMP_NTZ NOT NULL,
  EVENT_TYPE VARCHAR NOT NULL,
  LOCATION_CODE VARCHAR NOT NULL,
  TEMPERATURE_C NUMBER(8, 2)
);

CREATE TABLE IF NOT EXISTS RAW.INVENTORY_SNAPSHOTS (
  SNAPSHOT_DATE DATE NOT NULL,
  PLANT_ID VARCHAR NOT NULL,
  PART_ID VARCHAR NOT NULL,
  ON_HAND_QTY NUMBER(18, 3) NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW.LANDED_COSTS (
  SHIPMENT_ID VARCHAR NOT NULL,
  PRODUCT_COST_USD NUMBER(18, 2) NOT NULL,
  FREIGHT_USD NUMBER(18, 2) NOT NULL,
  DUTY_USD NUMBER(18, 2) NOT NULL,
  INSURANCE_USD NUMBER(18, 2) NOT NULL,
  HANDLING_USD NUMBER(18, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW.DOCUMENT_MANIFEST (
  DOCUMENT_ID VARCHAR NOT NULL,
  SHIPMENT_ID VARCHAR NOT NULL,
  DOCUMENT_TYPE VARCHAR NOT NULL,
  RELATIVE_PATH VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW.DOCUMENT_SCENARIOS (
  SHIPMENT_ID VARCHAR NOT NULL,
  EXPECTED_OUTCOME VARCHAR NOT NULL,
  EXPECTED_REASON VARCHAR NOT NULL
);
ALTER TABLE RAW.DOCUMENT_SCENARIOS ADD COLUMN IF NOT EXISTS EXPECTED_REASON VARCHAR;

CREATE TABLE IF NOT EXISTS RAW.DOCUMENT_EXTRACTION_FIXTURES (
  DOCUMENT_ID VARCHAR NOT NULL,
  PARSE_CONTENT VARCHAR,
  CONSIGNEE VARCHAR,
  PORT_OF_LOADING VARCHAR,
  PORT_OF_DISCHARGE VARCHAR,
  CONTAINER_NUMBER VARCHAR,
  CONTAINER_COUNT VARCHAR,
  GROSS_WEIGHT_KG VARCHAR,
  MARKS_AND_NUMBERS VARCHAR,
  MIN_CONFIDENCE FLOAT,
  PROCESSING_STATUS VARCHAR NOT NULL,
  ERROR_DETAILS VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW.DOCUMENT_FILE_REGISTRY (
  DOCUMENT_ID VARCHAR NOT NULL,
  SHIPMENT_ID VARCHAR NOT NULL,
  DOCUMENT_TYPE VARCHAR NOT NULL,
  RELATIVE_PATH VARCHAR NOT NULL,
  SHA256 VARCHAR NOT NULL,
  SIZE_BYTES NUMBER(38, 0) NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW.RUNTIME_CONFIG (
  CONFIG_KEY VARCHAR PRIMARY KEY,
  CONFIG_VALUE VARCHAR NOT NULL,
  CONFIG_NOTE VARCHAR,
  UPDATED_AT TIMESTAMP_LTZ NOT NULL
);

MERGE INTO RAW.RUNTIME_CONFIG target
USING (
  SELECT
    'DOCUMENT_PROCESSING_MODE' AS config_key,
    'FIXTURE' AS config_value,
    'Trial-safe deterministic extraction fixtures; set to AI only on an entitled account.'
      AS config_note
) source
ON target.config_key = source.config_key
WHEN NOT MATCHED THEN INSERT (
  config_key, config_value, config_note, updated_at
) VALUES (
  source.config_key, source.config_value, source.config_note, CURRENT_TIMESTAMP()
);

MERGE INTO RAW.RUNTIME_CONFIG target
USING (
  SELECT
    'EVIDENCE_RETRIEVAL_MODE' AS config_key,
    'SEMANTIC_VIEW' AS config_value,
    'Trial-safe governed retrieval through Cortex Analyst; use CORTEX_SEARCH only on an entitled account.'
      AS config_note
) source
ON target.config_key = source.config_key
WHEN NOT MATCHED THEN INSERT (
  config_key, config_value, config_note, updated_at
) VALUES (
  source.config_key, source.config_value, source.config_note, CURRENT_TIMESTAMP()
);
