USE WAREHOUSE VERICARGO_WH;
USE DATABASE VERICARGO_ONETRUTH;

-- The deployment helper uploads generated CSV files before this script runs.
ALTER STAGE RAW.CSV_STAGE REFRESH;
ALTER STAGE RAW.DOCUMENT_STAGE REFRESH;

TRUNCATE TABLE RAW.SUPPLIERS;
TRUNCATE TABLE RAW.PARTS;
TRUNCATE TABLE RAW.PLANTS;
TRUNCATE TABLE RAW.CUSTOMERS;
TRUNCATE TABLE RAW.PORTS;
TRUNCATE TABLE RAW.ORDERS;
TRUNCATE TABLE RAW.ORDER_LINES;
TRUNCATE TABLE RAW.SHIPMENTS;
TRUNCATE TABLE RAW.SHIPMENT_EVENTS;
TRUNCATE TABLE RAW.INVENTORY_SNAPSHOTS;
TRUNCATE TABLE RAW.LANDED_COSTS;
TRUNCATE TABLE RAW.DOCUMENT_MANIFEST;
TRUNCATE TABLE RAW.DOCUMENT_SCENARIOS;

COPY INTO RAW.SUPPLIERS
  FROM @RAW.CSV_STAGE/suppliers.csv
  FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_HEADER_FORMAT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.PARTS
  FROM @RAW.CSV_STAGE/parts.csv
  FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_HEADER_FORMAT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.PLANTS
  FROM @RAW.CSV_STAGE/plants.csv
  FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_HEADER_FORMAT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.CUSTOMERS
  FROM @RAW.CSV_STAGE/customers.csv
  FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_HEADER_FORMAT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.PORTS
  FROM @RAW.CSV_STAGE/ports.csv
  FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_HEADER_FORMAT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.ORDERS
  FROM @RAW.CSV_STAGE/orders.csv
  FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_HEADER_FORMAT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.ORDER_LINES
  FROM @RAW.CSV_STAGE/order_lines.csv
  FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_HEADER_FORMAT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.SHIPMENTS
  FROM @RAW.CSV_STAGE/shipments.csv
  FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_HEADER_FORMAT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.SHIPMENT_EVENTS
  FROM @RAW.CSV_STAGE/shipment_events.csv
  FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_HEADER_FORMAT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.INVENTORY_SNAPSHOTS
  FROM @RAW.CSV_STAGE/inventory_snapshots.csv
  FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_HEADER_FORMAT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.LANDED_COSTS
  FROM @RAW.CSV_STAGE/landed_costs.csv
  FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_HEADER_FORMAT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.DOCUMENT_MANIFEST
  FROM @RAW.CSV_STAGE/document_manifest.csv
  FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_HEADER_FORMAT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.DOCUMENT_SCENARIOS
  FROM @RAW.CSV_STAGE/document_scenarios.csv
  FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_HEADER_FORMAT')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'ABORT_STATEMENT';
